/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV.impl;

import fr.n7.jV.Action;
import fr.n7.jV.Condition;
import fr.n7.jV.JVPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.impl.ActionImpl#getDisplayCondition <em>Display Condition</em>}</li>
 *   <li>{@link fr.n7.jV.impl.ActionImpl#getEndCondition <em>End Condition</em>}</li>
 *   <li>{@link fr.n7.jV.impl.ActionImpl#getCondition <em>Condition</em>}</li>
 *   <li>{@link fr.n7.jV.impl.ActionImpl#getPrizesID <em>Prizes ID</em>}</li>
 *   <li>{@link fr.n7.jV.impl.ActionImpl#getConsumedID <em>Consumed ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActionImpl extends MinimalEObjectImpl.Container implements Action
{
  /**
   * The cached value of the '{@link #getDisplayCondition() <em>Display Condition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplayCondition()
   * @generated
   * @ordered
   */
  protected EList<Condition> displayCondition;

  /**
   * The cached value of the '{@link #getEndCondition() <em>End Condition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndCondition()
   * @generated
   * @ordered
   */
  protected EList<Condition> endCondition;

  /**
   * The cached value of the '{@link #getCondition() <em>Condition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition()
   * @generated
   * @ordered
   */
  protected EList<Condition> condition;

  /**
   * The cached value of the '{@link #getPrizesID() <em>Prizes ID</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrizesID()
   * @generated
   * @ordered
   */
  protected EList<String> prizesID;

  /**
   * The cached value of the '{@link #getConsumedID() <em>Consumed ID</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConsumedID()
   * @generated
   * @ordered
   */
  protected EList<String> consumedID;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JVPackage.Literals.ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Condition> getDisplayCondition()
  {
    if (displayCondition == null)
    {
      displayCondition = new EObjectContainmentEList<Condition>(Condition.class, this, JVPackage.ACTION__DISPLAY_CONDITION);
    }
    return displayCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Condition> getEndCondition()
  {
    if (endCondition == null)
    {
      endCondition = new EObjectContainmentEList<Condition>(Condition.class, this, JVPackage.ACTION__END_CONDITION);
    }
    return endCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Condition> getCondition()
  {
    if (condition == null)
    {
      condition = new EObjectContainmentEList<Condition>(Condition.class, this, JVPackage.ACTION__CONDITION);
    }
    return condition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getPrizesID()
  {
    if (prizesID == null)
    {
      prizesID = new EDataTypeEList<String>(String.class, this, JVPackage.ACTION__PRIZES_ID);
    }
    return prizesID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getConsumedID()
  {
    if (consumedID == null)
    {
      consumedID = new EDataTypeEList<String>(String.class, this, JVPackage.ACTION__CONSUMED_ID);
    }
    return consumedID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JVPackage.ACTION__DISPLAY_CONDITION:
        return ((InternalEList<?>)getDisplayCondition()).basicRemove(otherEnd, msgs);
      case JVPackage.ACTION__END_CONDITION:
        return ((InternalEList<?>)getEndCondition()).basicRemove(otherEnd, msgs);
      case JVPackage.ACTION__CONDITION:
        return ((InternalEList<?>)getCondition()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JVPackage.ACTION__DISPLAY_CONDITION:
        return getDisplayCondition();
      case JVPackage.ACTION__END_CONDITION:
        return getEndCondition();
      case JVPackage.ACTION__CONDITION:
        return getCondition();
      case JVPackage.ACTION__PRIZES_ID:
        return getPrizesID();
      case JVPackage.ACTION__CONSUMED_ID:
        return getConsumedID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JVPackage.ACTION__DISPLAY_CONDITION:
        getDisplayCondition().clear();
        getDisplayCondition().addAll((Collection<? extends Condition>)newValue);
        return;
      case JVPackage.ACTION__END_CONDITION:
        getEndCondition().clear();
        getEndCondition().addAll((Collection<? extends Condition>)newValue);
        return;
      case JVPackage.ACTION__CONDITION:
        getCondition().clear();
        getCondition().addAll((Collection<? extends Condition>)newValue);
        return;
      case JVPackage.ACTION__PRIZES_ID:
        getPrizesID().clear();
        getPrizesID().addAll((Collection<? extends String>)newValue);
        return;
      case JVPackage.ACTION__CONSUMED_ID:
        getConsumedID().clear();
        getConsumedID().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JVPackage.ACTION__DISPLAY_CONDITION:
        getDisplayCondition().clear();
        return;
      case JVPackage.ACTION__END_CONDITION:
        getEndCondition().clear();
        return;
      case JVPackage.ACTION__CONDITION:
        getCondition().clear();
        return;
      case JVPackage.ACTION__PRIZES_ID:
        getPrizesID().clear();
        return;
      case JVPackage.ACTION__CONSUMED_ID:
        getConsumedID().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JVPackage.ACTION__DISPLAY_CONDITION:
        return displayCondition != null && !displayCondition.isEmpty();
      case JVPackage.ACTION__END_CONDITION:
        return endCondition != null && !endCondition.isEmpty();
      case JVPackage.ACTION__CONDITION:
        return condition != null && !condition.isEmpty();
      case JVPackage.ACTION__PRIZES_ID:
        return prizesID != null && !prizesID.isEmpty();
      case JVPackage.ACTION__CONSUMED_ID:
        return consumedID != null && !consumedID.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (prizesID: ");
    result.append(prizesID);
    result.append(", consumedID: ");
    result.append(consumedID);
    result.append(')');
    return result.toString();
  }

} //ActionImpl
