/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV.impl;

import fr.n7.jV.JVPackage;
import fr.n7.jV.KnowledgeCondition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Knowledge Condition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.impl.KnowledgeConditionImpl#getKnowledgeRequiredID <em>Knowledge Required ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KnowledgeConditionImpl extends ConditionImpl implements KnowledgeCondition
{
  /**
   * The default value of the '{@link #getKnowledgeRequiredID() <em>Knowledge Required ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKnowledgeRequiredID()
   * @generated
   * @ordered
   */
  protected static final String KNOWLEDGE_REQUIRED_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getKnowledgeRequiredID() <em>Knowledge Required ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKnowledgeRequiredID()
   * @generated
   * @ordered
   */
  protected String knowledgeRequiredID = KNOWLEDGE_REQUIRED_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KnowledgeConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JVPackage.Literals.KNOWLEDGE_CONDITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getKnowledgeRequiredID()
  {
    return knowledgeRequiredID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKnowledgeRequiredID(String newKnowledgeRequiredID)
  {
    String oldKnowledgeRequiredID = knowledgeRequiredID;
    knowledgeRequiredID = newKnowledgeRequiredID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JVPackage.KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID, oldKnowledgeRequiredID, knowledgeRequiredID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JVPackage.KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID:
        return getKnowledgeRequiredID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JVPackage.KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID:
        setKnowledgeRequiredID((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JVPackage.KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID:
        setKnowledgeRequiredID(KNOWLEDGE_REQUIRED_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JVPackage.KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID:
        return KNOWLEDGE_REQUIRED_ID_EDEFAULT == null ? knowledgeRequiredID != null : !KNOWLEDGE_REQUIRED_ID_EDEFAULT.equals(knowledgeRequiredID);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (knowledgeRequiredID: ");
    result.append(knowledgeRequiredID);
    result.append(')');
    return result.toString();
  }

} //KnowledgeConditionImpl
