/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV.impl;

import fr.n7.jV.BOOLEAN;
import fr.n7.jV.JVPackage;
import fr.n7.jV.Person;
import fr.n7.jV.Places;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Places</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.impl.PlacesImpl#getStart <em>Start</em>}</li>
 *   <li>{@link fr.n7.jV.impl.PlacesImpl#getFinish <em>Finish</em>}</li>
 *   <li>{@link fr.n7.jV.impl.PlacesImpl#getPersons <em>Persons</em>}</li>
 *   <li>{@link fr.n7.jV.impl.PlacesImpl#getPathsID <em>Paths ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PlacesImpl extends GameElementImpl implements Places
{
  /**
   * The default value of the '{@link #getStart() <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected static final BOOLEAN START_EDEFAULT = BOOLEAN.TRUE;

  /**
   * The cached value of the '{@link #getStart() <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected BOOLEAN start = START_EDEFAULT;

  /**
   * The default value of the '{@link #getFinish() <em>Finish</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinish()
   * @generated
   * @ordered
   */
  protected static final BOOLEAN FINISH_EDEFAULT = BOOLEAN.TRUE;

  /**
   * The cached value of the '{@link #getFinish() <em>Finish</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinish()
   * @generated
   * @ordered
   */
  protected BOOLEAN finish = FINISH_EDEFAULT;

  /**
   * The cached value of the '{@link #getPersons() <em>Persons</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersons()
   * @generated
   * @ordered
   */
  protected EList<Person> persons;

  /**
   * The cached value of the '{@link #getPathsID() <em>Paths ID</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPathsID()
   * @generated
   * @ordered
   */
  protected EList<String> pathsID;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlacesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JVPackage.Literals.PLACES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BOOLEAN getStart()
  {
    return start;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStart(BOOLEAN newStart)
  {
    BOOLEAN oldStart = start;
    start = newStart == null ? START_EDEFAULT : newStart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JVPackage.PLACES__START, oldStart, start));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BOOLEAN getFinish()
  {
    return finish;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFinish(BOOLEAN newFinish)
  {
    BOOLEAN oldFinish = finish;
    finish = newFinish == null ? FINISH_EDEFAULT : newFinish;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JVPackage.PLACES__FINISH, oldFinish, finish));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Person> getPersons()
  {
    if (persons == null)
    {
      persons = new EObjectContainmentEList<Person>(Person.class, this, JVPackage.PLACES__PERSONS);
    }
    return persons;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getPathsID()
  {
    if (pathsID == null)
    {
      pathsID = new EDataTypeEList<String>(String.class, this, JVPackage.PLACES__PATHS_ID);
    }
    return pathsID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JVPackage.PLACES__PERSONS:
        return ((InternalEList<?>)getPersons()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JVPackage.PLACES__START:
        return getStart();
      case JVPackage.PLACES__FINISH:
        return getFinish();
      case JVPackage.PLACES__PERSONS:
        return getPersons();
      case JVPackage.PLACES__PATHS_ID:
        return getPathsID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JVPackage.PLACES__START:
        setStart((BOOLEAN)newValue);
        return;
      case JVPackage.PLACES__FINISH:
        setFinish((BOOLEAN)newValue);
        return;
      case JVPackage.PLACES__PERSONS:
        getPersons().clear();
        getPersons().addAll((Collection<? extends Person>)newValue);
        return;
      case JVPackage.PLACES__PATHS_ID:
        getPathsID().clear();
        getPathsID().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JVPackage.PLACES__START:
        setStart(START_EDEFAULT);
        return;
      case JVPackage.PLACES__FINISH:
        setFinish(FINISH_EDEFAULT);
        return;
      case JVPackage.PLACES__PERSONS:
        getPersons().clear();
        return;
      case JVPackage.PLACES__PATHS_ID:
        getPathsID().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JVPackage.PLACES__START:
        return start != START_EDEFAULT;
      case JVPackage.PLACES__FINISH:
        return finish != FINISH_EDEFAULT;
      case JVPackage.PLACES__PERSONS:
        return persons != null && !persons.isEmpty();
      case JVPackage.PLACES__PATHS_ID:
        return pathsID != null && !pathsID.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (start: ");
    result.append(start);
    result.append(", finish: ");
    result.append(finish);
    result.append(", pathsID: ");
    result.append(pathsID);
    result.append(')');
    return result.toString();
  }

} //PlacesImpl
