/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.projetIDM.Xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class JVUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.n7.JV");
	}

}
