/*
 * generated by Xtext 2.23.0
 */
package fr.n7.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJVScopeProvider extends DelegatingScopeProvider {
}
