/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.Action#getDisplayCondition <em>Display Condition</em>}</li>
 *   <li>{@link fr.n7.jV.Action#getEndCondition <em>End Condition</em>}</li>
 *   <li>{@link fr.n7.jV.Action#getCondition <em>Condition</em>}</li>
 *   <li>{@link fr.n7.jV.Action#getPrizesID <em>Prizes ID</em>}</li>
 *   <li>{@link fr.n7.jV.Action#getConsumedID <em>Consumed ID</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Display Condition</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Display Condition</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getAction_DisplayCondition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getDisplayCondition();

  /**
   * Returns the value of the '<em><b>End Condition</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Condition</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getAction_EndCondition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getEndCondition();

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getAction_Condition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getCondition();

  /**
   * Returns the value of the '<em><b>Prizes ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prizes ID</em>' attribute list.
   * @see fr.n7.jV.JVPackage#getAction_PrizesID()
   * @model unique="false"
   * @generated
   */
  EList<String> getPrizesID();

  /**
   * Returns the value of the '<em><b>Consumed ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consumed ID</em>' attribute list.
   * @see fr.n7.jV.JVPackage#getAction_ConsumedID()
   * @model unique="false"
   * @generated
   */
  EList<String> getConsumedID();

} // Action
