/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.jV.JVPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
