/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.GameElement#getId <em>Id</em>}</li>
 *   <li>{@link fr.n7.jV.GameElement#getPrizesID <em>Prizes ID</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getGameElement()
 * @model
 * @generated
 */
public interface GameElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see fr.n7.jV.JVPackage#getGameElement_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link fr.n7.jV.GameElement#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Prizes ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prizes ID</em>' attribute list.
   * @see fr.n7.jV.JVPackage#getGameElement_PrizesID()
   * @model unique="false"
   * @generated
   */
  EList<String> getPrizesID();

} // GameElement
