/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.Game#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jV.Game#getInventorySize <em>Inventory Size</em>}</li>
 *   <li>{@link fr.n7.jV.Game#getGameElements <em>Game Elements</em>}</li>
 *   <li>{@link fr.n7.jV.Game#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getGame()
 * @model
 * @generated
 */
public interface Game extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.jV.JVPackage#getGame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.jV.Game#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Inventory Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inventory Size</em>' attribute.
   * @see #setInventorySize(int)
   * @see fr.n7.jV.JVPackage#getGame_InventorySize()
   * @model
   * @generated
   */
  int getInventorySize();

  /**
   * Sets the value of the '{@link fr.n7.jV.Game#getInventorySize <em>Inventory Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inventory Size</em>' attribute.
   * @see #getInventorySize()
   * @generated
   */
  void setInventorySize(int value);

  /**
   * Returns the value of the '<em><b>Game Elements</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.GameElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Game Elements</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getGame_GameElements()
   * @model containment="true"
   * @generated
   */
  EList<GameElement> getGameElements();

  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Prize}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getGame_Objects()
   * @model containment="true"
   * @generated
   */
  EList<Prize> getObjects();

} // Game
