/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inventory Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.InventoryObject#getTransformationCondition <em>Transformation Condition</em>}</li>
 *   <li>{@link fr.n7.jV.InventoryObject#getObjectAfterTransformationID <em>Object After Transformation ID</em>}</li>
 *   <li>{@link fr.n7.jV.InventoryObject#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getInventoryObject()
 * @model
 * @generated
 */
public interface InventoryObject extends Prize
{
  /**
   * Returns the value of the '<em><b>Transformation Condition</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transformation Condition</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getInventoryObject_TransformationCondition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getTransformationCondition();

  /**
   * Returns the value of the '<em><b>Object After Transformation ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object After Transformation ID</em>' attribute.
   * @see #setObjectAfterTransformationID(String)
   * @see fr.n7.jV.JVPackage#getInventoryObject_ObjectAfterTransformationID()
   * @model
   * @generated
   */
  String getObjectAfterTransformationID();

  /**
   * Sets the value of the '{@link fr.n7.jV.InventoryObject#getObjectAfterTransformationID <em>Object After Transformation ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object After Transformation ID</em>' attribute.
   * @see #getObjectAfterTransformationID()
   * @generated
   */
  void setObjectAfterTransformationID(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see fr.n7.jV.JVPackage#getInventoryObject_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link fr.n7.jV.InventoryObject#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

} // InventoryObject
