/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.jV.JVFactory
 * @model kind="package"
 * @generated
 */
public interface JVPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jV";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/JV";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jV";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JVPackage eINSTANCE = fr.n7.jV.impl.JVPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.GameImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Inventory Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__INVENTORY_SIZE = 1;

  /**
   * The feature id for the '<em><b>Game Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GAME_ELEMENTS = 2;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__OBJECTS = 3;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.DescriptionImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__TEXT = 0;

  /**
   * The feature id for the '<em><b>Optional Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__OPTIONAL_TEXT = 1;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.OptionalTextImpl <em>Optional Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.OptionalTextImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getOptionalText()
   * @generated
   */
  int OPTIONAL_TEXT = 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_TEXT__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_TEXT__TEXT = 1;

  /**
   * The number of structural features of the '<em>Optional Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_TEXT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.GameElementImpl <em>Game Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.GameElementImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getGameElement()
   * @generated
   */
  int GAME_ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_ELEMENT__ID = 0;

  /**
   * The feature id for the '<em><b>Prizes ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_ELEMENT__PRIZES_ID = 1;

  /**
   * The number of structural features of the '<em>Game Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.PlacesImpl <em>Places</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.PlacesImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getPlaces()
   * @generated
   */
  int PLACES = 4;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES__ID = GAME_ELEMENT__ID;

  /**
   * The feature id for the '<em><b>Prizes ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES__PRIZES_ID = GAME_ELEMENT__PRIZES_ID;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES__START = GAME_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Finish</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES__FINISH = GAME_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES__PERSONS = GAME_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Paths ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES__PATHS_ID = GAME_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Places</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACES_FEATURE_COUNT = GAME_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.PrizeImpl <em>Prize</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.PrizeImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getPrize()
   * @generated
   */
  int PRIZE = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIZE__ID = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIZE__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Prize</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.ConditionImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 6;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.ObjectConditionImpl <em>Object Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.ObjectConditionImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getObjectCondition()
   * @generated
   */
  int OBJECT_CONDITION = 7;

  /**
   * The feature id for the '<em><b>Object Required ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_CONDITION__OBJECT_REQUIRED_ID = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_CONDITION__AMOUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Min Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_CONDITION__MIN_AMOUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Max Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_CONDITION__MAX_AMOUNT = CONDITION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Object Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.KnowledgeConditionImpl <em>Knowledge Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.KnowledgeConditionImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getKnowledgeCondition()
   * @generated
   */
  int KNOWLEDGE_CONDITION = 8;

  /**
   * The feature id for the '<em><b>Knowledge Required ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Knowledge Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.PersonImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 9;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ID = 0;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__VISIBLE = 1;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__MANDATORY = 2;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ACTIONS = 3;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.ActionImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getAction()
   * @generated
   */
  int ACTION = 10;

  /**
   * The feature id for the '<em><b>Display Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DISPLAY_CONDITION = 0;

  /**
   * The feature id for the '<em><b>End Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__END_CONDITION = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONDITION = 2;

  /**
   * The feature id for the '<em><b>Prizes ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PRIZES_ID = 3;

  /**
   * The feature id for the '<em><b>Consumed ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONSUMED_ID = 4;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.KnowledgeImpl <em>Knowledge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.KnowledgeImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getKnowledge()
   * @generated
   */
  int KNOWLEDGE = 11;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE__ID = PRIZE__ID;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE__DESCRIPTION = PRIZE__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE__VISIBLE = PRIZE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE__CONDITION = PRIZE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Knowledge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KNOWLEDGE_FEATURE_COUNT = PRIZE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.PathImpl <em>Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.PathImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getPath()
   * @generated
   */
  int PATH = 12;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__ID = GAME_ELEMENT__ID;

  /**
   * The feature id for the '<em><b>Prizes ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__PRIZES_ID = GAME_ELEMENT__PRIZES_ID;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__DESCRIPTION = GAME_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Open</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__OPEN = GAME_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Visible</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__VISIBLE = GAME_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__MANDATORY = GAME_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Consumed ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__CONSUMED_ID = GAME_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FEATURE_COUNT = GAME_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link fr.n7.jV.impl.InventoryObjectImpl <em>Inventory Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.impl.InventoryObjectImpl
   * @see fr.n7.jV.impl.JVPackageImpl#getInventoryObject()
   * @generated
   */
  int INVENTORY_OBJECT = 13;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVENTORY_OBJECT__ID = PRIZE__ID;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVENTORY_OBJECT__DESCRIPTION = PRIZE__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Transformation Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVENTORY_OBJECT__TRANSFORMATION_CONDITION = PRIZE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Object After Transformation ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVENTORY_OBJECT__OBJECT_AFTER_TRANSFORMATION_ID = PRIZE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVENTORY_OBJECT__SIZE = PRIZE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Inventory Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVENTORY_OBJECT_FEATURE_COUNT = PRIZE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.n7.jV.BOOLEAN <em>BOOLEAN</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jV.BOOLEAN
   * @see fr.n7.jV.impl.JVPackageImpl#getBOOLEAN()
   * @generated
   */
  int BOOLEAN = 14;


  /**
   * Returns the meta object for class '{@link fr.n7.jV.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see fr.n7.jV.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jV.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Game#getInventorySize <em>Inventory Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Inventory Size</em>'.
   * @see fr.n7.jV.Game#getInventorySize()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_InventorySize();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Game#getGameElements <em>Game Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Game Elements</em>'.
   * @see fr.n7.jV.Game#getGameElements()
   * @see #getGame()
   * @generated
   */
  EReference getGame_GameElements();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Game#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see fr.n7.jV.Game#getObjects()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Objects();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see fr.n7.jV.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Description#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see fr.n7.jV.Description#getText()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Text();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Description#getOptionalText <em>Optional Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Optional Text</em>'.
   * @see fr.n7.jV.Description#getOptionalText()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_OptionalText();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.OptionalText <em>Optional Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Optional Text</em>'.
   * @see fr.n7.jV.OptionalText
   * @generated
   */
  EClass getOptionalText();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.OptionalText#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Condition</em>'.
   * @see fr.n7.jV.OptionalText#getCondition()
   * @see #getOptionalText()
   * @generated
   */
  EReference getOptionalText_Condition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.OptionalText#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see fr.n7.jV.OptionalText#getText()
   * @see #getOptionalText()
   * @generated
   */
  EAttribute getOptionalText_Text();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.GameElement <em>Game Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Element</em>'.
   * @see fr.n7.jV.GameElement
   * @generated
   */
  EClass getGameElement();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.GameElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.jV.GameElement#getId()
   * @see #getGameElement()
   * @generated
   */
  EAttribute getGameElement_Id();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.jV.GameElement#getPrizesID <em>Prizes ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Prizes ID</em>'.
   * @see fr.n7.jV.GameElement#getPrizesID()
   * @see #getGameElement()
   * @generated
   */
  EAttribute getGameElement_PrizesID();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Places <em>Places</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Places</em>'.
   * @see fr.n7.jV.Places
   * @generated
   */
  EClass getPlaces();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Places#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see fr.n7.jV.Places#getStart()
   * @see #getPlaces()
   * @generated
   */
  EAttribute getPlaces_Start();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Places#getFinish <em>Finish</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Finish</em>'.
   * @see fr.n7.jV.Places#getFinish()
   * @see #getPlaces()
   * @generated
   */
  EAttribute getPlaces_Finish();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Places#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see fr.n7.jV.Places#getPersons()
   * @see #getPlaces()
   * @generated
   */
  EReference getPlaces_Persons();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.jV.Places#getPathsID <em>Paths ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Paths ID</em>'.
   * @see fr.n7.jV.Places#getPathsID()
   * @see #getPlaces()
   * @generated
   */
  EAttribute getPlaces_PathsID();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Prize <em>Prize</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prize</em>'.
   * @see fr.n7.jV.Prize
   * @generated
   */
  EClass getPrize();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Prize#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.jV.Prize#getId()
   * @see #getPrize()
   * @generated
   */
  EAttribute getPrize_Id();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jV.Prize#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see fr.n7.jV.Prize#getDescription()
   * @see #getPrize()
   * @generated
   */
  EReference getPrize_Description();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see fr.n7.jV.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.ObjectCondition <em>Object Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Condition</em>'.
   * @see fr.n7.jV.ObjectCondition
   * @generated
   */
  EClass getObjectCondition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.ObjectCondition#getObjectRequiredID <em>Object Required ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Object Required ID</em>'.
   * @see fr.n7.jV.ObjectCondition#getObjectRequiredID()
   * @see #getObjectCondition()
   * @generated
   */
  EAttribute getObjectCondition_ObjectRequiredID();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.ObjectCondition#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see fr.n7.jV.ObjectCondition#getAmount()
   * @see #getObjectCondition()
   * @generated
   */
  EAttribute getObjectCondition_Amount();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.ObjectCondition#getMinAmount <em>Min Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Amount</em>'.
   * @see fr.n7.jV.ObjectCondition#getMinAmount()
   * @see #getObjectCondition()
   * @generated
   */
  EAttribute getObjectCondition_MinAmount();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.ObjectCondition#getMaxAmount <em>Max Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Amount</em>'.
   * @see fr.n7.jV.ObjectCondition#getMaxAmount()
   * @see #getObjectCondition()
   * @generated
   */
  EAttribute getObjectCondition_MaxAmount();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.KnowledgeCondition <em>Knowledge Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Knowledge Condition</em>'.
   * @see fr.n7.jV.KnowledgeCondition
   * @generated
   */
  EClass getKnowledgeCondition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.KnowledgeCondition#getKnowledgeRequiredID <em>Knowledge Required ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Knowledge Required ID</em>'.
   * @see fr.n7.jV.KnowledgeCondition#getKnowledgeRequiredID()
   * @see #getKnowledgeCondition()
   * @generated
   */
  EAttribute getKnowledgeCondition_KnowledgeRequiredID();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see fr.n7.jV.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Person#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.jV.Person#getId()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Id();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Person#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visible</em>'.
   * @see fr.n7.jV.Person#getVisible()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Visible();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Person#getMandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mandatory</em>'.
   * @see fr.n7.jV.Person#getMandatory()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Mandatory();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Person#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see fr.n7.jV.Person#getActions()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Actions();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see fr.n7.jV.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Action#getDisplayCondition <em>Display Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Display Condition</em>'.
   * @see fr.n7.jV.Action#getDisplayCondition()
   * @see #getAction()
   * @generated
   */
  EReference getAction_DisplayCondition();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Action#getEndCondition <em>End Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>End Condition</em>'.
   * @see fr.n7.jV.Action#getEndCondition()
   * @see #getAction()
   * @generated
   */
  EReference getAction_EndCondition();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Action#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Condition</em>'.
   * @see fr.n7.jV.Action#getCondition()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Condition();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.jV.Action#getPrizesID <em>Prizes ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Prizes ID</em>'.
   * @see fr.n7.jV.Action#getPrizesID()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_PrizesID();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.jV.Action#getConsumedID <em>Consumed ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Consumed ID</em>'.
   * @see fr.n7.jV.Action#getConsumedID()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_ConsumedID();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Knowledge <em>Knowledge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Knowledge</em>'.
   * @see fr.n7.jV.Knowledge
   * @generated
   */
  EClass getKnowledge();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jV.Knowledge#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Visible</em>'.
   * @see fr.n7.jV.Knowledge#getVisible()
   * @see #getKnowledge()
   * @generated
   */
  EReference getKnowledge_Visible();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Knowledge#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Condition</em>'.
   * @see fr.n7.jV.Knowledge#getCondition()
   * @see #getKnowledge()
   * @generated
   */
  EReference getKnowledge_Condition();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.Path <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path</em>'.
   * @see fr.n7.jV.Path
   * @generated
   */
  EClass getPath();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jV.Path#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see fr.n7.jV.Path#getDescription()
   * @see #getPath()
   * @generated
   */
  EReference getPath_Description();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Path#getOpen <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Open</em>'.
   * @see fr.n7.jV.Path#getOpen()
   * @see #getPath()
   * @generated
   */
  EReference getPath_Open();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.Path#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Visible</em>'.
   * @see fr.n7.jV.Path#getVisible()
   * @see #getPath()
   * @generated
   */
  EReference getPath_Visible();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.Path#getMandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mandatory</em>'.
   * @see fr.n7.jV.Path#getMandatory()
   * @see #getPath()
   * @generated
   */
  EAttribute getPath_Mandatory();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.jV.Path#getConsumedID <em>Consumed ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Consumed ID</em>'.
   * @see fr.n7.jV.Path#getConsumedID()
   * @see #getPath()
   * @generated
   */
  EAttribute getPath_ConsumedID();

  /**
   * Returns the meta object for class '{@link fr.n7.jV.InventoryObject <em>Inventory Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inventory Object</em>'.
   * @see fr.n7.jV.InventoryObject
   * @generated
   */
  EClass getInventoryObject();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jV.InventoryObject#getTransformationCondition <em>Transformation Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transformation Condition</em>'.
   * @see fr.n7.jV.InventoryObject#getTransformationCondition()
   * @see #getInventoryObject()
   * @generated
   */
  EReference getInventoryObject_TransformationCondition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.InventoryObject#getObjectAfterTransformationID <em>Object After Transformation ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Object After Transformation ID</em>'.
   * @see fr.n7.jV.InventoryObject#getObjectAfterTransformationID()
   * @see #getInventoryObject()
   * @generated
   */
  EAttribute getInventoryObject_ObjectAfterTransformationID();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jV.InventoryObject#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see fr.n7.jV.InventoryObject#getSize()
   * @see #getInventoryObject()
   * @generated
   */
  EAttribute getInventoryObject_Size();

  /**
   * Returns the meta object for enum '{@link fr.n7.jV.BOOLEAN <em>BOOLEAN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>BOOLEAN</em>'.
   * @see fr.n7.jV.BOOLEAN
   * @generated
   */
  EEnum getBOOLEAN();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JVFactory getJVFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.GameImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Inventory Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__INVENTORY_SIZE = eINSTANCE.getGame_InventorySize();

    /**
     * The meta object literal for the '<em><b>Game Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GAME_ELEMENTS = eINSTANCE.getGame_GameElements();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__OBJECTS = eINSTANCE.getGame_Objects();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.DescriptionImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__TEXT = eINSTANCE.getDescription_Text();

    /**
     * The meta object literal for the '<em><b>Optional Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__OPTIONAL_TEXT = eINSTANCE.getDescription_OptionalText();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.OptionalTextImpl <em>Optional Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.OptionalTextImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getOptionalText()
     * @generated
     */
    EClass OPTIONAL_TEXT = eINSTANCE.getOptionalText();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTIONAL_TEXT__CONDITION = eINSTANCE.getOptionalText_Condition();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTIONAL_TEXT__TEXT = eINSTANCE.getOptionalText_Text();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.GameElementImpl <em>Game Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.GameElementImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getGameElement()
     * @generated
     */
    EClass GAME_ELEMENT = eINSTANCE.getGameElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_ELEMENT__ID = eINSTANCE.getGameElement_Id();

    /**
     * The meta object literal for the '<em><b>Prizes ID</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_ELEMENT__PRIZES_ID = eINSTANCE.getGameElement_PrizesID();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.PlacesImpl <em>Places</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.PlacesImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getPlaces()
     * @generated
     */
    EClass PLACES = eINSTANCE.getPlaces();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLACES__START = eINSTANCE.getPlaces_Start();

    /**
     * The meta object literal for the '<em><b>Finish</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLACES__FINISH = eINSTANCE.getPlaces_Finish();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLACES__PERSONS = eINSTANCE.getPlaces_Persons();

    /**
     * The meta object literal for the '<em><b>Paths ID</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLACES__PATHS_ID = eINSTANCE.getPlaces_PathsID();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.PrizeImpl <em>Prize</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.PrizeImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getPrize()
     * @generated
     */
    EClass PRIZE = eINSTANCE.getPrize();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIZE__ID = eINSTANCE.getPrize_Id();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIZE__DESCRIPTION = eINSTANCE.getPrize_Description();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.ConditionImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.ObjectConditionImpl <em>Object Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.ObjectConditionImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getObjectCondition()
     * @generated
     */
    EClass OBJECT_CONDITION = eINSTANCE.getObjectCondition();

    /**
     * The meta object literal for the '<em><b>Object Required ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_CONDITION__OBJECT_REQUIRED_ID = eINSTANCE.getObjectCondition_ObjectRequiredID();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_CONDITION__AMOUNT = eINSTANCE.getObjectCondition_Amount();

    /**
     * The meta object literal for the '<em><b>Min Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_CONDITION__MIN_AMOUNT = eINSTANCE.getObjectCondition_MinAmount();

    /**
     * The meta object literal for the '<em><b>Max Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_CONDITION__MAX_AMOUNT = eINSTANCE.getObjectCondition_MaxAmount();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.KnowledgeConditionImpl <em>Knowledge Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.KnowledgeConditionImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getKnowledgeCondition()
     * @generated
     */
    EClass KNOWLEDGE_CONDITION = eINSTANCE.getKnowledgeCondition();

    /**
     * The meta object literal for the '<em><b>Knowledge Required ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KNOWLEDGE_CONDITION__KNOWLEDGE_REQUIRED_ID = eINSTANCE.getKnowledgeCondition_KnowledgeRequiredID();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.PersonImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__ID = eINSTANCE.getPerson_Id();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__VISIBLE = eINSTANCE.getPerson_Visible();

    /**
     * The meta object literal for the '<em><b>Mandatory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__MANDATORY = eINSTANCE.getPerson_Mandatory();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__ACTIONS = eINSTANCE.getPerson_Actions();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.ActionImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Display Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__DISPLAY_CONDITION = eINSTANCE.getAction_DisplayCondition();

    /**
     * The meta object literal for the '<em><b>End Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__END_CONDITION = eINSTANCE.getAction_EndCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONDITION = eINSTANCE.getAction_Condition();

    /**
     * The meta object literal for the '<em><b>Prizes ID</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__PRIZES_ID = eINSTANCE.getAction_PrizesID();

    /**
     * The meta object literal for the '<em><b>Consumed ID</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__CONSUMED_ID = eINSTANCE.getAction_ConsumedID();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.KnowledgeImpl <em>Knowledge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.KnowledgeImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getKnowledge()
     * @generated
     */
    EClass KNOWLEDGE = eINSTANCE.getKnowledge();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KNOWLEDGE__VISIBLE = eINSTANCE.getKnowledge_Visible();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KNOWLEDGE__CONDITION = eINSTANCE.getKnowledge_Condition();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.PathImpl <em>Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.PathImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getPath()
     * @generated
     */
    EClass PATH = eINSTANCE.getPath();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH__DESCRIPTION = eINSTANCE.getPath_Description();

    /**
     * The meta object literal for the '<em><b>Open</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH__OPEN = eINSTANCE.getPath_Open();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH__VISIBLE = eINSTANCE.getPath_Visible();

    /**
     * The meta object literal for the '<em><b>Mandatory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH__MANDATORY = eINSTANCE.getPath_Mandatory();

    /**
     * The meta object literal for the '<em><b>Consumed ID</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH__CONSUMED_ID = eINSTANCE.getPath_ConsumedID();

    /**
     * The meta object literal for the '{@link fr.n7.jV.impl.InventoryObjectImpl <em>Inventory Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.impl.InventoryObjectImpl
     * @see fr.n7.jV.impl.JVPackageImpl#getInventoryObject()
     * @generated
     */
    EClass INVENTORY_OBJECT = eINSTANCE.getInventoryObject();

    /**
     * The meta object literal for the '<em><b>Transformation Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INVENTORY_OBJECT__TRANSFORMATION_CONDITION = eINSTANCE.getInventoryObject_TransformationCondition();

    /**
     * The meta object literal for the '<em><b>Object After Transformation ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVENTORY_OBJECT__OBJECT_AFTER_TRANSFORMATION_ID = eINSTANCE.getInventoryObject_ObjectAfterTransformationID();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVENTORY_OBJECT__SIZE = eINSTANCE.getInventoryObject_Size();

    /**
     * The meta object literal for the '{@link fr.n7.jV.BOOLEAN <em>BOOLEAN</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jV.BOOLEAN
     * @see fr.n7.jV.impl.JVPackageImpl#getBOOLEAN()
     * @generated
     */
    EEnum BOOLEAN = eINSTANCE.getBOOLEAN();

  }

} //JVPackage
