/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.KnowledgeCondition#getKnowledgeRequiredID <em>Knowledge Required ID</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getKnowledgeCondition()
 * @model
 * @generated
 */
public interface KnowledgeCondition extends Condition
{
  /**
   * Returns the value of the '<em><b>Knowledge Required ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge Required ID</em>' attribute.
   * @see #setKnowledgeRequiredID(String)
   * @see fr.n7.jV.JVPackage#getKnowledgeCondition_KnowledgeRequiredID()
   * @model
   * @generated
   */
  String getKnowledgeRequiredID();

  /**
   * Sets the value of the '{@link fr.n7.jV.KnowledgeCondition#getKnowledgeRequiredID <em>Knowledge Required ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Knowledge Required ID</em>' attribute.
   * @see #getKnowledgeRequiredID()
   * @generated
   */
  void setKnowledgeRequiredID(String value);

} // KnowledgeCondition
