/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.Knowledge#getVisible <em>Visible</em>}</li>
 *   <li>{@link fr.n7.jV.Knowledge#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getKnowledge()
 * @model
 * @generated
 */
public interface Knowledge extends Prize
{
  /**
   * Returns the value of the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' containment reference.
   * @see #setVisible(Condition)
   * @see fr.n7.jV.JVPackage#getKnowledge_Visible()
   * @model containment="true"
   * @generated
   */
  Condition getVisible();

  /**
   * Sets the value of the '{@link fr.n7.jV.Knowledge#getVisible <em>Visible</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' containment reference.
   * @see #getVisible()
   * @generated
   */
  void setVisible(Condition value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getKnowledge_Condition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getCondition();

} // Knowledge
