/**
 * generated by Xtext 2.23.0
 */
package fr.n7.jV;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Places</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jV.Places#getStart <em>Start</em>}</li>
 *   <li>{@link fr.n7.jV.Places#getFinish <em>Finish</em>}</li>
 *   <li>{@link fr.n7.jV.Places#getPersons <em>Persons</em>}</li>
 *   <li>{@link fr.n7.jV.Places#getPathsID <em>Paths ID</em>}</li>
 * </ul>
 *
 * @see fr.n7.jV.JVPackage#getPlaces()
 * @model
 * @generated
 */
public interface Places extends GameElement
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jV.BOOLEAN}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see fr.n7.jV.BOOLEAN
   * @see #setStart(BOOLEAN)
   * @see fr.n7.jV.JVPackage#getPlaces_Start()
   * @model
   * @generated
   */
  BOOLEAN getStart();

  /**
   * Sets the value of the '{@link fr.n7.jV.Places#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see fr.n7.jV.BOOLEAN
   * @see #getStart()
   * @generated
   */
  void setStart(BOOLEAN value);

  /**
   * Returns the value of the '<em><b>Finish</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jV.BOOLEAN}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finish</em>' attribute.
   * @see fr.n7.jV.BOOLEAN
   * @see #setFinish(BOOLEAN)
   * @see fr.n7.jV.JVPackage#getPlaces_Finish()
   * @model
   * @generated
   */
  BOOLEAN getFinish();

  /**
   * Sets the value of the '{@link fr.n7.jV.Places#getFinish <em>Finish</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finish</em>' attribute.
   * @see fr.n7.jV.BOOLEAN
   * @see #getFinish()
   * @generated
   */
  void setFinish(BOOLEAN value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jV.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see fr.n7.jV.JVPackage#getPlaces_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Paths ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paths ID</em>' attribute list.
   * @see fr.n7.jV.JVPackage#getPlaces_PathsID()
   * @model unique="false"
   * @generated
   */
  EList<String> getPathsID();

} // Places
